<?php if (!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true) die();?>
<?$APPLICATION->SetTitle("Поиск");?>
<div class="content">
	<?$APPLICATION->IncludeComponent(
		"bitrix:search.page",
		"tags",
		Array(
			"TAGS_SORT" => "NAME",
			"TAGS_PAGE_ELEMENTS" => "20",
			"TAGS_PERIOD" => "",
			"TAGS_URL_SEARCH" => "",
			"TAGS_INHERIT" => "Y",
			"FONT_MAX" => "50",
			"FONT_MIN" => "10",
			"COLOR_NEW" => "000000",
			"COLOR_OLD" => "C8C8C8",
			"PERIOD_NEW_TAGS" => "",
			"SHOW_CHAIN" => "Y",
			"COLOR_TYPE" => "Y",
			"WIDTH" => "100%",
			"USE_SUGGEST" => "N",
			"SHOW_RATING" => "Y",
			"RATING_TYPE" => "",
			"PATH_TO_USER_PROFILE" => "#SITE_DIR#people/user/#USER_ID#/",
			"AJAX_MODE" => "N",
			"RESTART" => "N",
			"NO_WORD_LOGIC" => "N",
			"USE_LANGUAGE_GUESS" => "Y",
			"CHECK_DATES" => "Y",
			"USE_TITLE_RANK" => "N",
			"DEFAULT_SORT" => "rank",
			"FILTER_NAME" => "",
			"SHOW_WHERE" => "N",
//			"arrWHERE" => array("forum","iblock_news","blog"),
			"SHOW_WHEN" => "N",
			"PAGE_RESULT_COUNT" => "10",
			"CACHE_TYPE" => "A",
			"CACHE_TIME" => "3600",
			"CACHE_NOTES" => "",
			"DISPLAY_TOP_PAGER" => "Y",
			"DISPLAY_BOTTOM_PAGER" => "Y",
			"PAGER_TITLE" => "Результаты поиска",
			"PAGER_SHOW_ALWAYS" => "Y",
			"PAGER_TEMPLATE" => "estelife",
			"arrFILTER" => array("iblock_news","iblock_clinics","iblock_learning"),
			"arrFILTER_iblock_news" => array("all"),
			"arrFILTER_iblock_clinics" => array("all"),
			"arrFILTER_iblock_learning" => "all",
			"AJAX_OPTION_JUMP" => "N",
			"AJAX_OPTION_STYLE" => "Y",
			"AJAX_OPTION_HISTORY" => "N",
			"AJAX_OPTION_ADDITIONAL" => ""
		)
	);?>

</div>