ALTER TABLE `b_estelife_clinics` DROP FOREIGN KEY `fk_estelife_clinics_4`;
ALTER TABLE `b_estelife_services` DROP FOREIGN KEY `fk_estelife_services_1`;
ALTER TABLE `b_estelife_service_concreate` DROP FOREIGN KEY `fk_estelife_service_concreate_1`;
ALTER TABLE `b_estelife_service_concreate` DROP FOREIGN KEY `fk_estelife_service_concreate_2`;
ALTER TABLE `b_estelife_clinic_services` DROP FOREIGN KEY `fk_estelife_clinic_services_1`;
ALTER TABLE `b_estelife_clinic_services` DROP FOREIGN KEY `fk_estelife_clinic_services_2`;
ALTER TABLE `b_estelife_clinic_services` DROP FOREIGN KEY `fk_estelife_clinic_services_3`;
ALTER TABLE `b_estelife_clinic_services` DROP FOREIGN KEY `fk_estelife_clinic_services_4`;
ALTER TABLE `b_estelife_clinic_gallery` DROP FOREIGN KEY `fk_estelife_clinic_gallery_2`;
ALTER TABLE `b_estelife_clinic_akzii` DROP FOREIGN KEY `fk_estelife_clinic_akzii_1`;
ALTER TABLE `b_estelife_clinic_akzii` DROP FOREIGN KEY `fk_estelife_clinic_akzii_2`;
ALTER TABLE `b_estelife_clinic_contacts` DROP FOREIGN KEY `fk_estelife_clinic_contacts_2`;
ALTER TABLE `b_akzii_photos` DROP FOREIGN KEY `fk_akzii_photos_4`;
ALTER TABLE `b_estelife_clinic_photos` DROP FOREIGN KEY `fk_estelife_clinic_photos_1`;
ALTER TABLE `b_estelife_busy_hours` DROP FOREIGN KEY `fk_estelife_busy_hours_1`;
drop table if exists `b_estelife_clinics`;
drop table if exists `b_estelife_specializations`;
drop table if exists `b_estelife_services`;
drop table if exists `b_estelife_service_concreate`;
drop table if exists `b_estelife_clinic_services`;
drop table if exists `b_estelife_clinic_gallery`;
drop table if exists `b_estelife_akzii`;
drop table if exists `b_estelife_clinic_akzii`;
drop table if exists `b_estelife_clinic_contacts`;
drop table if exists `b_akzii_photos`;
drop table if exists `b_estelife_clinic_photos`;
drop table if exists `b_estelife_busy_hours`;